// Generates shaders/generated/osd_font.hlsli: an 8x12 bitmap font (ASCII 32..126)
// for the in-game OSD, rasterized from DejaVu Sans Mono Bold with stb_truetype.
//
//   g++ -std=c++17 -O2 -Ithird_party/stb tools/make_osd_font.cpp -o make_osd_font
//   ./make_osd_font /usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf shaders/generated/osd_font.hlsli

#define STB_TRUETYPE_IMPLEMENTATION
#include "stb_truetype.h"

#include <cmath>
#include <cstdio>
#include <fstream>
#include <iterator>
#include <vector>

int main(int argc, char** argv) {
    if (argc < 3) {
        std::fprintf(stderr, "usage: make_osd_font <font.ttf> <out.hlsli>\n");
        return 2;
    }
    std::ifstream f(argv[1], std::ios::binary);
    std::vector<unsigned char> blob((std::istreambuf_iterator<char>(f)), std::istreambuf_iterator<char>());
    stbtt_fontinfo font;
    if (blob.empty() || !stbtt_InitFont(&font, blob.data(), stbtt_GetFontOffsetForIndex(blob.data(), 0))) return 1;
    const int W = 8, H = 12;
    const float scale = stbtt_ScaleForPixelHeight(&font, 14.0f);
    int ascent = 0, descent = 0, gap = 0;
    stbtt_GetFontVMetrics(&font, &ascent, &descent, &gap);
    const int baseline = int(std::lround(ascent * scale)) - 1;
    std::vector<unsigned> rows; // 95 glyphs * 12 rows, 8 bits per row
    for (int ch = 32; ch < 127; ++ch) {
        std::vector<unsigned char> bmp(size_t(W) * H, 0);
        int x0, y0, x1, y1;
        stbtt_GetCodepointBitmapBox(&font, ch, scale, scale, &x0, &y0, &x1, &y1);
        int adv, lsb;
        stbtt_GetCodepointHMetrics(&font, ch, &adv, &lsb);
        const int gw = x1 - x0, gh = y1 - y0;
        std::vector<unsigned char> g(size_t(std::max(gw, 1)) * std::max(gh, 1), 0);
        if (gw > 0 && gh > 0) stbtt_MakeCodepointBitmap(&font, g.data(), gw, gh, gw, scale, scale, ch);
        const int ox = (W - int(std::lround(adv * scale))) / 2 + x0;
        for (int y = 0; y < gh; ++y)
            for (int x = 0; x < gw; ++x) {
                const int px = ox + x, py = baseline + y0 + y;
                if (px >= 0 && px < W && py >= 0 && py < H) bmp[size_t(py) * W + px] = std::max(bmp[size_t(py) * W + px], g[size_t(y) * gw + x]);
            }
        for (int y = 0; y < H; ++y) {
            unsigned bits = 0;
            for (int x = 0; x < W; ++x)
                if (bmp[size_t(y) * W + x] >= 90) bits |= 1u << x;
            rows.push_back(bits);
        }
    }
    std::ofstream o(argv[2]);
    o << "// AUTO-GENERATED by tools/make_osd_font.cpp from DejaVu Sans Mono Bold. Do not edit.\n";
    o << "// 8x12 glyphs for ASCII 32..126; 4 rows per uint (8 bits each, bit x = column x).\n";
    o << "#define OSD_GLYPH_W 8\n#define OSD_GLYPH_H 12\n";
    o << "static const uint kOsdFont[" << rows.size() / 4 << "] = {\n";
    for (size_t i = 0; i < rows.size(); i += 4) {
        unsigned v = rows[i] | (rows[i + 1] << 8) | (rows[i + 2] << 16) | (rows[i + 3] << 24);
        char buf[32];
        std::snprintf(buf, sizeof(buf), "0x%08Xu,", v);
        o << buf << ((i / 4) % 8 == 7 ? "\n" : " ");
    }
    o << "};\n";
    std::printf("wrote %zu glyph rows\n", rows.size());
    return 0;
}
