#include "renderer/ShaderLibrary.h"

#include "core/Log.h"

// Generated by CMake: one header per shader variant (g_<name> byte arrays)
#include "bgn_shader_includes.inc"

namespace bgn {

namespace {
enum class Kind { CS, VS, PS };
struct Blob {
    const char* name;
    Kind kind;
    const void* data;
    size_t size;
};
#define CS Kind::CS
#define VS Kind::VS
#define PS Kind::PS
const Blob kBlobs[] = {
#define BGN_SHADER(name, kind) {#name, kind, g_##name, sizeof(g_##name)},
#include "bgn_shader_table.inc"
#undef BGN_SHADER
};
#undef CS
#undef VS
#undef PS
static_assert(sizeof(kBlobs) / sizeof(kBlobs[0]) == static_cast<size_t>(ShaderId::Count), "shader table mismatch");
} // namespace

const char* shaderName(ShaderId id) { return kBlobs[static_cast<int>(id)].name; }

bool ShaderLibrary::init(ID3D11Device* device) {
    release();
    for (int i = 0; i < kCount; ++i) {
        const Blob& b = kBlobs[i];
        HRESULT hr = E_FAIL;
        switch (b.kind) {
        case Kind::CS: hr = device->CreateComputeShader(b.data, b.size, nullptr, &cs_[i]); break;
        case Kind::VS: hr = device->CreateVertexShader(b.data, b.size, nullptr, &vs_[i]); break;
        case Kind::PS: hr = device->CreatePixelShader(b.data, b.size, nullptr, &ps_[i]); break;
        }
        if (FAILED(hr)) {
            error_ = std::string("failed to create shader ") + b.name + ": " + hrToString(hr);
            BGN_LOG_ERROR("Shaders", "{}", error_);
            return false;
        }
    }
    BGN_LOG_DEBUG("Shaders", "{} shaders created", kCount);
    return true;
}

void ShaderLibrary::release() {
    for (auto& s : cs_) s.Reset();
    for (auto& s : vs_) s.Reset();
    for (auto& s : ps_) s.Reset();
}

ID3D11ComputeShader* ShaderLibrary::cs(ShaderId id) const { return cs_[static_cast<int>(id)].Get(); }
ID3D11VertexShader* ShaderLibrary::vs(ShaderId id) const { return vs_[static_cast<int>(id)].Get(); }
ID3D11PixelShader* ShaderLibrary::ps(ShaderId id) const { return ps_[static_cast<int>(id)].Get(); }

} // namespace bgn
